#Created By: Mary Kozuch
#Last Edited: 4/13/2021
version: "3.9"
services:
  #WORKS------------------------------------
  Jupyter:
    build: ./jupyter
    image: jupyter
    environment:
      - DISABLE_AUTH=true
    ports:
      - "8887:8887"
    logging:
      driver: none
  #WORKS------------------------------------
  Rstudio:
    image: rocker/rstudio
    environment:
      - PASSWORD=pass
    ports:
      - "8787:8787"
    logging:
      driver: none
  #WORKS------------------------------------
  #Spyder: -> website
  #WORKS------------------------------------
  #IBM_SAS: -> website
  #WORKS------------------------------------
  #PASSWORD=root
  Git: 
   build: ./git
   image: git
   ports:
     - "2201:22"
   stdin_open: true
   tty: true
   privileged: true
   command: "/usr/sbin/sshd -D"
   logging:
      driver: none
  #WORKS------------------------------------
  #PASSWORD=orange
  Orange:
    image: acopar/orange-docker
    ports:
      - "5901:5901"
      - "6901:6901"
    logging:
      driver: none
  #WORKS------------------------------------
  Visual_studio:
    image: codercom/code-server:latest
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=password
    logging:
      driver: none
  #WORKS------------------------------------
  #PASSWORD=hduser
  Apache_Hadoop:
    build: ./hadoop
    image: hadoop
    volumes:
      - ./docker-hadoop-data/:/home/hduser/hdfs-data/
      - ./docker-hadoop-logs/:/opt/hadoop/logs/
    stdin_open: true
    tty: true
    ports:
      - "2202:22"
      - 2181:2181
      - 39534:39534
      - 9001:9000
      - 50070:50070
      - 50010:50010
      - 50020:50020
      - 50075:50075
      - 50090:50090
      - 8030:8030
      - 8031:8031
      - 8032:8032
      - 8033:8033
      - 8088:8088
      - 8040:8040
      - 8042:8042
      - 13562:13562
      - 47784:47784
      - 10020:10020
      - 19888:19888
    logging:
      driver: none
  #WORKS------------------------------------
  #test connection to 7077
  spark-master: 
    image: sdesilva26/spark_master:0.0.2
    hostname: spark
    container_name: spark
    ports:
      - "7077:7077"
      - "8082:8082"
    logging:
      driver: none
    environment: 
      - SPARK_MASTER_WEBUI_PORT=8082
  spark-worker:
    image: sdesilva26/spark_worker:0.0.2
    ports:
      - "8081:8081"
    links:
      - spark-master
    environment:
      - CORES=3
      - MEMORY=15G
    logging:
      driver: none
   #
  #https://towardsdatascience.com/diy-apache-spark-docker-bb4f11c10d24
  #WORKS------------------------------------
  #Tableau: -> website
  #WORKS------------------------------------
  #PASSWORD=admin
  #SonarQube:
  #  image: sonarqube:7.9.2-community
  #  ports:
  #    - "9000:9000"
  #    - "9092:9092"
  #  environment:
  #    - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  #  logging:
  #    driver: none
  #SonarScanner:
  #  image: sonarsource/sonar-scanner-cli
  #  links:
  #    - SonarQube
  #  volumes:
  #    - ./git:/usr/src
  #  stdin_open: true
  #  tty: true
  #  privileged: true
  #  environment:
  #    #- SONAR_TOKEN...??
  #    - SONAR_HOST_URL=http://SonarQube:9000
  #    #- sonar.login="admin"
  #    #- sonar.password="admin"
  #  command:
  #    - "-Dsonar.projectKey='test'"
  #WORKS------------------------------------
  TensorFlow:
    build: ./tensorflow
    image: tensorflow
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    privileged: true
  #WORKS------------------------------------
  Markdown:
    image: v4tech/markdown-editor
    ports:
      - "12345:80"
    logging:
      driver: none
  app:
    image: app
    build: .
    environment:
      - DISPLAY=192.168.1.34:0.0
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - .:/root/working
      - ./test:/sonar
    ports:
      - "2200:22"
    links:
      - "Jupyter"
      - "Rstudio"
      - "Git"
      - "Orange"
      - "Visual_studio"
      - "Apache_Hadoop"
      - "spark-master:Apache_Spark"
    #  - "SonarQube"
      - "TensorFlow"
      - "Markdown"
