FROM tensorflow/tensorflow:latest-jupyter
#CMD ["jupyter", "notebook", "-y", "--generate-config"]
#CMD ["jupyter", "notebook", "--no-browser", "--ServerApp.token=''","--ServerApp.password=''","--allow-root"]
